### ISSUE TITLE
algorithm improvements

### ISSUE THREAD

**Issue by zappybiby** [zappybiby/EuroTruckAutopilot#10]
1. use sobel operator (because Canny has not been very effective in my attempts)
2. use otsu thresholding 
3. kalman filter (https://medium.com/giscle/how-we-used-kalman-filter-for-detecting-indian-road-lane-at-night-990206c5d668)
4. gamma correction (https://docs.opencv.org/3.4/d3/dc1/tutorial_basic_linear_transform.html)
5. normalized cross correlation (https://docs.opencv.org/3.4/de/da9/tutorial_template_matching.html)

**Comment by zappybiby** [comment]
Results so far:

CLAHE Histogram Equalization seems very promising and improves the detection of lane lines
Canny was better than Sobel but not by much - still having poor results
Kalman filter is honking complex so no go

**Bilateral Filtering** is something I Just learned about - it smooths the image but keeps edges sharp. Significant improvement with that over standard Gaussian blur.

**Comment by ajchili** [comment]
Once an optimal method is determined, [integrations with other langauges](https://wiki.python.org/moin/IntegratingPythonWithOtherLanguages) could be done to further improve performance.
