### ISSUE TITLE
Need to detect two lines at the same time

### ISSUE THREAD

**Issue by zappybiby** [zappybiby/EuroTruckAutopilot#2]
We are currently drawing one line at a time. We need to draw two lines simultaneously in order to calculate the center of the lane.

**Comment by ajchili** [comment]
Is this issue the main priority? We should also get footage to test with so that we do not have to constantly hop into the game to develop.

**Comment by zappybiby** [comment]
#3 has higher priority than this, but both will still need to be dealt with in order to have ETA successfully  drive the truck.

By implementing #3, we would have an array containing the average of the last _x_ lines detected. We don't necessarily have to find the two lines simultaneously, as the lines are detected so fast that the average of them would provide us with two lines on each side of the lane. Then we could use the histogram method described in #4 to get the x-positions of the two lines in order to calculate the center of the lane.

I made a 30-second ["stress test" video](https://drive.google.com/file/d/1rx1cd1OUTceHLSOa2i1h9Lra4futW-FN/view?usp=sharing) that goes through a variety of lighting situations. You can have opencv read from that video by using the following code in `grab_window()`:

```
cap = cv2.VideoCapture('EuroStressTest.mp4')

while(cap.isOpened()):
    ret, frame = cap.read()
    cv2.imshow('frame',frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()
```

**Comment by zappybiby** [comment]
Implemented in https://github.com/zappybiby/EuroTruckAutopilot/commit/e1beb015fdab00a6728d2bb304b3412e53ad27e0
